-- 목포 : 붉은 벽돌의 시간
-- Supabase SQL Editor에서 한 번 실행하는 기록관 테이블과 보안 정책입니다.

create table if not exists public.memory_records (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now(),
  status text not null default 'visible',
  constraint memory_records_message_length
    check (char_length(btrim(message)) between 1 and 100),
  constraint memory_records_no_contact_details
    check (
      message !~* '(https?://|www\.|[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}|01[016789][ -]?[0-9]{3,4}[ -]?[0-9]{4})'
    ),
  constraint memory_records_status
    check (status in ('visible', 'hidden'))
);

alter table public.memory_records enable row level security;

-- 공개 브라우저에는 조회와 새 기록 등록만 허용합니다.
-- 기존 기록의 수정과 삭제 권한은 Supabase 관리자에게만 남깁니다.
revoke all on table public.memory_records from anon, authenticated;
grant select (id, message, created_at) on table public.memory_records to anon, authenticated;
grant insert (message) on table public.memory_records to anon, authenticated;
grant usage, select on sequence public.memory_records_id_seq to anon, authenticated;

drop policy if exists "public can read visible memories" on public.memory_records;
create policy "public can read visible memories"
  on public.memory_records
  for select
  to anon, authenticated
  using (status = 'visible');

drop policy if exists "public can add a short anonymous memory" on public.memory_records;
create policy "public can add a short anonymous memory"
  on public.memory_records
  for insert
  to anon, authenticated
  with check (
    status = 'visible'
    and char_length(btrim(message)) between 1 and 100
    and message !~* '(https?://|www\.|[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}|01[016789][ -]?[0-9]{3,4}[ -]?[0-9]{4})'
  );

create index if not exists memory_records_visible_created_at_idx
  on public.memory_records (created_at desc)
  where status = 'visible';

comment on table public.memory_records is
  '붉은 벽돌 기록관의 익명 100자 답장. 관리자는 status를 hidden으로 바꾸어 숨길 수 있다.';
